### ISSUE TITLE
KeyError when Trying to upload audience

### ISSUE THREAD

**Issue by marianmazarovici** [twitterdev/twitter-python-ads-sdk#71] opened 2016-07-04 16:55 UTC
> File "/Users/Salieri/PhpstormProjects/brightmatter-lengo/social_networks/twitter.py", line 135, in build_audience
>     tailored_audience = TailoredAudience.create(account, handles_file.name, audience_name, handle_type)
>   File "/usr/local/lib/python3.5/site-packages/twitter_ads/audience.py", line 31, in create
>     getattr(audience, '**update_audience**')(upload.perform(), list_type, TA_OPERATIONS.ADD)
>   File "/usr/local/lib/python3.5/site-packages/twitter_ads/http.py", line 263, in perform
>     self.**upload_chunk(location, chunk_size, bytes, bytes_start, bytes_read)
>   File "/usr/local/lib/python3.5/site-packages/twitter_ads/http.py", line 318, in __upload_chunk
>     domain=self._DEFAULT_DOMAIN, headers=headers, body=bytes).perform()
>   File "/usr/local/lib/python3.5/site-packages/twitter_ads/http.py", line 73, in perform
>     response = self.__oauth_request()
>   File "/usr/local/lib/python3.5/site-packages/twitter_ads/http.py", line 103, in __oauth_request
>     body=response.raw, raw_body=raw_response_body)
>   File "/usr/local/lib/python3.5/site-packages/twitter_ads/http.py", line 132, in __init**
>     if headers['content-type'] == 'application/gzip':
>   File "/usr/local/lib/python3.5/site-packages/requests/structures.py", line 54, in **getitem**
>     return self._store[key.lower()][1]
> KeyError: 'content-type'

The error appears when a permanent redirect is issued

> 2016-07-04 17:20:41,905 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ton.twitter.com
> 2016-07-04 17:20:43,748 - requests.packages.urllib3.connectionpool - DEBUG - "PUT /1.1/ton/data/ta_partner/31825624/ykbdzgruR2JL372.txt?resumable=true&resumeId=173310  HTTP/1.1" 308 0

**Comment by juanshishido** [comment] 2016-12-11 06:30
Thanks for raising this, @marianmazarovici. Fixed in #80.

(Note: this issue is a duplicate of #79.)

**Closed by juanshishido** 2016-12-11 06:30 UTC
