### ISSUE TITLE
7.0.2 Type Error in Oauth Request

### ISSUE THREAD

**Issue by chris-smith-publicis** [twitterdev/twitter-python-ads-sdk#268] opened 2020-10-13 12:45 UTC
Ever since 2020-10-08 we have been receiving the following error when trying to make a LineItem.async_stats_job_result call. 

File "D:\python\lib\site-packages\twitter_ads\http.py", line 105, in __oauth_request
    url = self.__domain() + self._resource
TypeError: can only concatenate str (not "bytes") to str

**Comment by tushdante** [comment] 2020-10-13 15:43
Hey @chris-smith-publicis can you provide steps to reproduce the issue?

**Comment by seanpdwyer7** [comment] 2020-10-13 21:47
Any one find a solution to this? I'm seeing the same issues with async requests

**Comment by chris-smith-publicis** [comment] 2020-10-13 21:56
> 
> 
> Hey @chris-smith-publicis can you provide steps to reproduce the issue?

FrankOnBeach provided a similar example

**Comment by TuscanyBotha** [comment] 2020-10-14 16:02
I'm seeing the same error.

**Comment by seanpdwyer7** [comment] 2020-10-15 16:29
@tushdante has Anybody been able to find a solution to this issue? It looks like it might be within the SDK itself. As I've been cronning the async job every hour and seems to break in the afternoon before working later in the day

**Comment by chris-smith-publicis** [comment] 2020-10-15 16:42
> 
> 
> @tushdante has Anybody been able to find a solution to this issue? It looks like it might be within the SDK itself. As I've been cronning the async job every hour and seems to break in the afternoon before working later in the day

It is definitely in the SDK itself because it is a response that the oauth handler is recieiving is not in a format it expects

**Comment by tushdante** [comment] 2020-10-15 18:10
Hey all, so it turns out that the issue isn't originating from the SDK. We're seeing intermittent downtime with the async analytics endpoints causing the `result.url` field on the API response to being set to `null`, here:

```
for result in async_stats_job_results:
    async_data.append(LineItem.async_stats_job_data(account, url=result.url))
```

One workaround would be to increase the `seconds` in `time.sleep(seconds)` to something larger to allow for more processing time prior to fetching the results, or adding a check to ensure the results are available. 

On the SDK side of things, it sounds like we'd want to add functionality to handle these types of cases (where an API endpoint is unavailable) but given current constraints this won't be addressed in the short term. That being said, our PRs are open and we're more than happy to assist in case someone from this thread wants to contribute.

**Comment by seanpdwyer7** [comment] 2020-10-15 18:21
Thanks @tushdante! I'm curious how much time your team would add to the time sleep. I've added around 90 seconds to delay the response and still seeing the oauth error. Would you be able to provide an example of how the second workaround would work?

**Comment by chris-smith-publicis** [comment] 2020-10-15 19:05
@seanpdwyer7 I went a little extreme and threw a sleep(random.randint(120,240)) in there... it is most likely over kill but I did get a return set

**Comment by tushdante** [comment] 2020-10-15 19:20
@seanpdwyer7 one potential approach could be to modify [twitter_ads/analytics.py](https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/twitter_ads/analytics.py#L98) to poll the GET stats endpoint and check to check for `status: "SUCCESS` prior to fetching the URL/results (in L#105). There would be a need to add some retry logic there, in case the status is `PROCESSING`. Definitely open to discussions/ideas if there's a better alternative.

**Comment by tushdante** [comment] 2020-10-15 21:29
Closing out this issue, [resolution here](https://github.com/twitterdev/twitter-python-ads-sdk/issues/268#issuecomment-709539542)

**Closed by tushdante** 2020-10-15 21:29 UTC
