### ISSUE TITLE
Expand TargetingCriteria to allow for batch creation

### ISSUE THREAD

**Issue by frewsxcv** [twitterdev/twitter-python-ads-sdk#76] opened 2016-07-13 02:11 UTC
Wrap around [this API endpoints](https://dev.twitter.com/ads/reference/post/batch/accounts/%3Aaccount_id/targeting_criteria).

**Comment by jaakko-sf** [comment] 2016-08-31 17:39
marking as a duplicate of #82

**Closed by jaakko-sf** 2016-08-31 17:39 UTC
Labels: duplicate
